apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-provisioner-admin
  namespace: rukpak-system
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles"]
  verbs: ["*"]
