apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plain-v0-provisioner-admin
rules:
- apiGroups: ["core.rukpak.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "roles"]
  verbs: ["*"]
